/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateQuestionAnswersDto } from '../../models/create-question-answers-dto';
import { QuestionAnswersResponseDto } from '../../models/question-answers-response-dto';

export interface CreateQuestionAnswers$Params {
      body: CreateQuestionAnswersDto
}

export function createQuestionAnswers(http: HttpClient, rootUrl: string, params: CreateQuestionAnswers$Params, context?: HttpContext): Observable<StrictHttpResponse<QuestionAnswersResponseDto>> {
  const rb = new RequestBuilder(rootUrl, createQuestionAnswers.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QuestionAnswersResponseDto>;
    })
  );
}

createQuestionAnswers.PATH = '/api/question-answers';
