/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuestionAnswersResponseDto } from '../../models/question-answers-response-dto';
import { UpdateQuestionAnswersDto } from '../../models/update-question-answers-dto';

export interface UpdateQuestionAnswers$Params {
  id: string;
      body: UpdateQuestionAnswersDto
}

export function updateQuestionAnswers(http: HttpClient, rootUrl: string, params: UpdateQuestionAnswers$Params, context?: HttpContext): Observable<StrictHttpResponse<QuestionAnswersResponseDto>> {
  const rb = new RequestBuilder(rootUrl, updateQuestionAnswers.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QuestionAnswersResponseDto>;
    })
  );
}

updateQuestionAnswers.PATH = '/api/question-answers/{id}';
