/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAllSessions } from '../fn/sessions/get-all-sessions';
import { GetAllSessions$Params } from '../fn/sessions/get-all-sessions';
import { getSessionsByYear } from '../fn/sessions/get-sessions-by-year';
import { GetSessionsByYear$Params } from '../fn/sessions/get-sessions-by-year';
import { SessionConfigurationDto } from '../models/session-configuration-dto';

@Injectable({ providedIn: 'root' })
export class SessionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllSessions()` */
  static readonly GetAllSessionsPath = '/sessions';

  /**
   * Get all sessions.
   *
   * Retrieves all available counseling sessions
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllSessions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSessions$Response(params?: GetAllSessions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SessionConfigurationDto>>> {
    return getAllSessions(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all sessions.
   *
   * Retrieves all available counseling sessions
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllSessions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSessions(params?: GetAllSessions$Params, context?: HttpContext): Observable<Array<SessionConfigurationDto>> {
    return this.getAllSessions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SessionConfigurationDto>>): Array<SessionConfigurationDto> => r.body)
    );
  }

  /** Path part for operation `getSessionsByYear()` */
  static readonly GetSessionsByYearPath = '/sessions/{year}';

  /**
   * Get sessions by year.
   *
   * Retrieves counseling sessions for a specific year
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSessionsByYear()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSessionsByYear$Response(params: GetSessionsByYear$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SessionConfigurationDto>>> {
    return getSessionsByYear(this.http, this.rootUrl, params, context);
  }

  /**
   * Get sessions by year.
   *
   * Retrieves counseling sessions for a specific year
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSessionsByYear$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSessionsByYear(params: GetSessionsByYear$Params, context?: HttpContext): Observable<Array<SessionConfigurationDto>> {
    return this.getSessionsByYear$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SessionConfigurationDto>>): Array<SessionConfigurationDto> => r.body)
    );
  }

}
