// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using csi_mkd_premarital_app_BE.Data;

#nullable disable

namespace csi_mkd_premarital_app_BE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204170916_AddPremaritalOutsideKeralaRegistration")]
    partial class AddPremaritalOutsideKeralaRegistration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConfirmationRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ChurchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ConfirmationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Consent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CounsellingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PriestName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("Id");

                    b.HasIndex("SubmittedDate");

                    b.ToTable("ConfirmationRegistrations");
                });

            modelBuilder.Entity("Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConfirmationRegistrationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationRegistrationId");

                    b.HasIndex("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$Bs8bRm0NuP.QM7kTlBc/6OSw.G2Dq3MjX4yZEduT1LcrNXUtNj5D.",
                            Username = "csimkdmarry@gmail.com"
                        });
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("KeyValues")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.ConfirmationDocument", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VicarLetterUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("RegistrationId");

                    b.ToTable("ConfirmationDocuments");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.EmailConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailBodyTemplate")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SenderPassword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("EmailConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailBodyTemplate = "<p>Hello {Name},</p>\n                <p>Thank you for registering with us.</p>\n                <p>Your registration for the counselling session has been successfully completed.</p>\n                <p>We look forward to seeing you there.</p>\n                <p>Best regards,<br/>CSI MKD Counselling Team</p>",
                            EmailSubject = "Confirmation: CSI MKD Counselling Session Registration",
                            SenderEmail = "csimkdmarry@gmail.com",
                            SenderPassword = "chvj gmhp bzov tllv"
                        });
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.GeneralDocument", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RegistrationId");

                    b.ToTable("GeneralDocuments");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.GeneralRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int?>("ChurchId")
                        .HasColumnType("integer");

                    b.Property<bool>("Declaration")
                        .HasColumnType("boolean");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("PaymentStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PriestName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Id");

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("SubmittedAt");

                    b.ToTable("GeneralRegistrations");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Instructors", "public");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.ParticipantOutsideKerala", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.ToTable("ParticipantsOutsideKerala");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.PremaritalDocument", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VicarLetterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("RegistrationId");

                    b.ToTable("PremaritalDocuments");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.PremaritalOutsideKeralaDocument", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VicarLetterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("RegistrationId");

                    b.ToTable("PremaritalOutsideKeralaDocuments");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.PremaritalOutsideKeralaRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ChurchId")
                        .HasColumnType("integer");

                    b.Property<string>("PriestName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("SessionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("SessionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("SubmittedAt");

                    b.ToTable("PremaritalOutsideKeralaRegistrations");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.PremaritalRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("ChurchActivitiesJson")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ChurchId")
                        .HasColumnType("integer");

                    b.Property<string>("ChurchName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DateOfMarriage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Declaration")
                        .HasColumnType("boolean");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FianceName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("PaymentStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PriestName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Id");

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("SessionId");

                    b.HasIndex("SubmittedAt");

                    b.ToTable("PremaritalRegistrations");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.SessionConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartDate");

                    b.ToTable("SessionConfigurations");
                });

            modelBuilder.Entity("Participant", b =>
                {
                    b.HasOne("ConfirmationRegistration", "ConfirmationRegistration")
                        .WithMany("Participants")
                        .HasForeignKey("ConfirmationRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmationRegistration");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.ConfirmationDocument", b =>
                {
                    b.HasOne("ConfirmationRegistration", "ConfirmationRegistration")
                        .WithOne("ConfirmationDocument")
                        .HasForeignKey("csi_mkd_premarital_app_BE.Models.ConfirmationDocument", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmationRegistration");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.GeneralDocument", b =>
                {
                    b.HasOne("csi_mkd_premarital_app_BE.Models.GeneralRegistration", "GeneralRegistration")
                        .WithOne("GeneralDocument")
                        .HasForeignKey("csi_mkd_premarital_app_BE.Models.GeneralDocument", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralRegistration");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.ParticipantOutsideKerala", b =>
                {
                    b.HasOne("csi_mkd_premarital_app_BE.Models.PremaritalOutsideKeralaRegistration", "PremaritalOutsideKeralaRegistration")
                        .WithMany("Participants")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PremaritalOutsideKeralaRegistration");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.PremaritalDocument", b =>
                {
                    b.HasOne("csi_mkd_premarital_app_BE.Models.PremaritalRegistration", "PremaritalRegistration")
                        .WithOne("PremaritalDocument")
                        .HasForeignKey("csi_mkd_premarital_app_BE.Models.PremaritalDocument", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PremaritalRegistration");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.PremaritalOutsideKeralaDocument", b =>
                {
                    b.HasOne("csi_mkd_premarital_app_BE.Models.PremaritalOutsideKeralaRegistration", "PremaritalOutsideKeralaRegistration")
                        .WithOne("PremaritalOutsideKeralaDocument")
                        .HasForeignKey("csi_mkd_premarital_app_BE.Models.PremaritalOutsideKeralaDocument", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PremaritalOutsideKeralaRegistration");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.PremaritalRegistration", b =>
                {
                    b.HasOne("csi_mkd_premarital_app_BE.Models.SessionConfiguration", "SessionConfiguration")
                        .WithMany("PremaritalRegistrations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SessionConfiguration");
                });

            modelBuilder.Entity("ConfirmationRegistration", b =>
                {
                    b.Navigation("ConfirmationDocument")
                        .IsRequired();

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.GeneralRegistration", b =>
                {
                    b.Navigation("GeneralDocument");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.PremaritalOutsideKeralaRegistration", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("PremaritalOutsideKeralaDocument");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.PremaritalRegistration", b =>
                {
                    b.Navigation("PremaritalDocument");
                });

            modelBuilder.Entity("csi_mkd_premarital_app_BE.Models.SessionConfiguration", b =>
                {
                    b.Navigation("PremaritalRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
