// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using csi_mkd_premarital_app_BE.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace csi_mkd_premarital_app_BE.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class PremaritalOutsideKeralaDocumentEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "csi_mkd_premarital_app_BE.Models.PremaritalOutsideKeralaDocument",
                typeof(PremaritalOutsideKeralaDocument),
                baseEntityType,
                propertyCount: 3,
                navigationCount: 1,
                foreignKeyCount: 1,
                keyCount: 1);

            var registrationId = runtimeEntityType.AddProperty(
                "RegistrationId",
                typeof(Guid),
                propertyInfo: typeof(PremaritalOutsideKeralaDocument).GetProperty("RegistrationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PremaritalOutsideKeralaDocument).GetField("<RegistrationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            registrationId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var submittedAt = runtimeEntityType.AddProperty(
                "SubmittedAt",
                typeof(DateTime),
                propertyInfo: typeof(PremaritalOutsideKeralaDocument).GetProperty("SubmittedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PremaritalOutsideKeralaDocument).GetField("<SubmittedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            submittedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var vicarLetterUrl = runtimeEntityType.AddProperty(
                "VicarLetterUrl",
                typeof(string),
                propertyInfo: typeof(PremaritalOutsideKeralaDocument).GetProperty("VicarLetterUrl", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PremaritalOutsideKeralaDocument).GetField("<VicarLetterUrl>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            vicarLetterUrl.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { registrationId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("RegistrationId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true);

            var premaritalOutsideKeralaRegistration = declaringEntityType.AddNavigation("PremaritalOutsideKeralaRegistration",
                runtimeForeignKey,
                onDependent: true,
                typeof(PremaritalOutsideKeralaRegistration),
                propertyInfo: typeof(PremaritalOutsideKeralaDocument).GetProperty("PremaritalOutsideKeralaRegistration", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PremaritalOutsideKeralaDocument).GetField("<PremaritalOutsideKeralaRegistration>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var premaritalOutsideKeralaDocument = principalEntityType.AddNavigation("PremaritalOutsideKeralaDocument",
                runtimeForeignKey,
                onDependent: false,
                typeof(PremaritalOutsideKeralaDocument),
                propertyInfo: typeof(PremaritalOutsideKeralaRegistration).GetProperty("PremaritalOutsideKeralaDocument", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PremaritalOutsideKeralaRegistration).GetField("<PremaritalOutsideKeralaDocument>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "PremaritalOutsideKeralaDocuments");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
