/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionConfigurationDto {
  endDate?: string;
  id?: number;
  isActive?: boolean;
  sessionName?: string;
  startDate?: string;
  submittedDate?: string;
}
