// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Newtonsoft.Json.Linq;
using csi_mkd_premarital_app_BE.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace csi_mkd_premarital_app_BE.data
{
    [EntityFrameworkInternal]
    public partial class ClassFeedbackDetailEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "csi_mkd_premarital_app_BE.Models.ClassFeedbackDetail",
                typeof(ClassFeedbackDetail),
                baseEntityType,
                propertyCount: 6,
                navigationCount: 2,
                foreignKeyCount: 1,
                keyCount: 1);

            var classFeedbackEntryClassFeedbackid = runtimeEntityType.AddProperty(
                "ClassFeedbackEntryClassFeedbackid",
                typeof(string),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 4000);

            var classFeedbackEntryClassFeedbackPremaritalRegistrationId = runtimeEntityType.AddProperty(
                "ClassFeedbackEntryClassFeedbackPremaritalRegistrationId",
                typeof(Guid),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            classFeedbackEntryClassFeedbackPremaritalRegistrationId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");

            var classFeedbackEntryId = runtimeEntityType.AddProperty(
                "ClassFeedbackEntryId",
                typeof(int),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var date = runtimeEntityType.AddProperty(
                "Date",
                typeof(DateTime),
                propertyInfo: typeof(ClassFeedbackDetail).GetProperty("Date", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClassFeedbackDetail).GetField("<Date>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                providerPropertyType: typeof(DateTime),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            var instructorId = runtimeEntityType.AddProperty(
                "InstructorId",
                typeof(int),
                propertyInfo: typeof(ClassFeedbackDetail).GetProperty("InstructorId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClassFeedbackDetail).GetField("<InstructorId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var __jObject = runtimeEntityType.AddProperty(
                "__jObject",
                typeof(JObject),
                nullable: true,
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore);
            __jObject.AddAnnotation("Cosmos:PropertyName", "");

            var key = runtimeEntityType.AddKey(
                new[] { classFeedbackEntryClassFeedbackid, classFeedbackEntryClassFeedbackPremaritalRegistrationId, classFeedbackEntryId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ClassFeedbackEntryClassFeedbackid"), declaringEntityType.FindProperty("ClassFeedbackEntryClassFeedbackPremaritalRegistrationId"), declaringEntityType.FindProperty("ClassFeedbackEntryId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("ClassFeedbackid"), principalEntityType.FindProperty("ClassFeedbackPremaritalRegistrationId"), principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true,
                requiredDependent: true,
                ownership: true);

            var detail = principalEntityType.AddNavigation("Detail",
                runtimeForeignKey,
                onDependent: false,
                typeof(ClassFeedbackDetail),
                propertyInfo: typeof(ClassFeedbackEntry).GetProperty("Detail", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClassFeedbackEntry).GetField("<Detail>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                eagerLoaded: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
