// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using csi_mkd_premarital_app_BE.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace csi_mkd_premarital_app_BE.data
{
    [EntityFrameworkInternal]
    public partial class FeedbackRatingsEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "csi_mkd_premarital_app_BE.Models.FeedbackRatings",
                typeof(FeedbackRatings),
                baseEntityType,
                propertyCount: 5,
                foreignKeyCount: 1,
                keyCount: 1);

            var feedbackDocumentid = runtimeEntityType.AddProperty(
                "FeedbackDocumentid",
                typeof(string),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 500);
            feedbackDocumentid.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var engagement = runtimeEntityType.AddProperty(
                "Engagement",
                typeof(int),
                propertyInfo: typeof(FeedbackRatings).GetProperty("Engagement", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FeedbackRatings).GetField("<Engagement>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            engagement.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var organization = runtimeEntityType.AddProperty(
                "Organization",
                typeof(int),
                propertyInfo: typeof(FeedbackRatings).GetProperty("Organization", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FeedbackRatings).GetField("<Organization>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            organization.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var quality = runtimeEntityType.AddProperty(
                "Quality",
                typeof(int),
                propertyInfo: typeof(FeedbackRatings).GetProperty("Quality", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FeedbackRatings).GetField("<Quality>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            quality.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var relevance = runtimeEntityType.AddProperty(
                "Relevance",
                typeof(int),
                propertyInfo: typeof(FeedbackRatings).GetProperty("Relevance", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FeedbackRatings).GetField("<Relevance>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            relevance.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { feedbackDocumentid });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("FeedbackDocumentid") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true,
                requiredDependent: true,
                ownership: true);

            var ratings = principalEntityType.AddNavigation("Ratings",
                runtimeForeignKey,
                onDependent: false,
                typeof(FeedbackRatings),
                propertyInfo: typeof(FeedbackDocument).GetProperty("Ratings", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FeedbackDocument).GetField("<Ratings>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                eagerLoaded: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "FeedbackDocument");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
