/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BackupResponse } from '../../models/backup-response';

export interface TriggerBackup$Params {
}

export function triggerBackup(http: HttpClient, rootUrl: string, params?: TriggerBackup$Params, context?: HttpContext): Observable<StrictHttpResponse<BackupResponse>> {
  const rb = new RequestBuilder(rootUrl, triggerBackup.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BackupResponse>;
    })
  );
}

triggerBackup.PATH = '/backup/trigger';
