/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppFeedbackDto {
  improvements?: string | null;
  likedMost?: string | null;
  locale?: string | null;
  page?: string | null;
  rating?: number;
}
