/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ConfirmationDocumentDto {
  registrationId?: number;
  vicarLetterUrl: string | null;
}
