/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeedbackDocumentDto {
  classId?: number;
  comments?: string | null;
  date: string;
  engagementRating: number;
  improvements?: string | null;
  instructorName?: string | null;
  location?: string | null;
  organizationRating: number;
  platform?: string | null;
  premaritalRegistrationId: number;
  qualityRating: number;
  relevanceRating: number;
  sessionDuration?: number | null;
  sessionTitle?: string | null;
  source?: string | null;
  valuable?: string | null;
}
