/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeedbackRatingsDto {
  average?: number;
  engagement?: number;
  organization?: number;
  quality?: number;
  relevance?: number;
}
