/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeedbackTextDto {
  comments?: string | null;
  hasDetailedFeedback?: boolean;
  improvements?: string | null;
  totalCharacters?: number;
  valuable?: string | null;
}
