/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GeneralRegisterDto {
  address: string | null;
  age?: number;
  churchId?: number | null;
  declaration?: boolean;
  education: string | null;
  email: string | null;
  fatherName: string | null;
  firstName: string | null;
  lastName: string | null;
  maritalStatus: string | null;
  occupation: string | null;
  paymentStatus?: boolean;
  phone: string | null;
  priestName?: string | null;
  recaptchaToken: string | null;
  sessionType: string | null;
  sex: string | null;
}
