/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InstructorRatingBreakdownDto {
  averageEngagement?: number;
  averageOrganization?: number;
  averageQuality?: number;
  averageRelevance?: number;
}
