/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InstructorRatingBreakdownDto } from '../models/instructor-rating-breakdown-dto';
export interface InstructorRatingDto {
  averageRating?: number;
  instructorId?: number;
  instructorName?: string | null;
  qualification?: string | null;
  ratingBreakdown?: InstructorRatingBreakdownDto;
  totalFeedbackCount?: number;
}
