/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InstructorDto {
  createdAt?: string;
  createdBy?: string | null;
  id?: number;
  lastModifiedAt?: string | null;
  lastModifiedBy?: string | null;
  name: string;
  qualification: string;
}
