/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ParticipantOutsideKeralaDto } from '../models/participant-outside-kerala-dto';
import { TimeZoneOption } from '../models/time-zone-option';
export interface PremaritalOutsideKeralaRegisterDto {
  churchId?: number | null;
  participants: Array<ParticipantOutsideKeralaDto>;
  priestName?: string | null;
  sessionEndDate: string;
  sessionStartDate: string;
  timeZone: TimeZoneOption;
}
