/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum TimeZoneOption {
  AsiaKolkata = 'Asia/Kolkata',
  AsiaDubai = 'Asia/Dubai',
  AsiaKuwait = 'Asia/Kuwait',
  AsiaMuscat = 'Asia/Muscat',
  AsiaQatar = 'Asia/Qatar',
  AsiaBahrain = 'Asia/Bahrain',
  AsiaSingapore = 'Asia/Singapore',
  AustraliaBrisbane = 'Australia/Brisbane',
  EuropeLondon = 'Europe/London',
  EuropeDublin = 'Europe/Dublin',
  AmericaNewYork = 'America/New_York',
  AmericaToronto = 'America/Toronto',
  AmericaChicago = 'America/Chicago',
  AmericaDetroit = 'America/Detroit',
  AmericaLosAngeles = 'America/Los_Angeles',
  Utc = 'UTC'
}
