/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePremaritalRegisterDto {
  address: string | null;
  age: number;
  choirMember?: boolean | null;
  churchId?: number | null;
  dateOfMarriage?: string | null;
  days: string | null;
  declaration: boolean;
  education: string | null;
  email: string | null;
  fatherName: string | null;
  fianceName?: string | null;
  firstName: string | null;
  lastName: string | null;
  occupation: string | null;
  other?: string | null;
  paymentStatus?: boolean;
  phone: string | null;
  priestName?: string | null;
  sessionId: number;
  sex: string | null;
  ssTeacher?: boolean | null;
  youthFellowship?: boolean | null;
}
