/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ParticipantDto } from '../models/participant-dto';
export interface UpdateConfirmationRegisterDto {
  churchId?: number | null;
  confirmationDate?: string;
  counsellingDate?: string;
  deletedParticipantIds?: Array<string> | null;
  participants?: Array<ParticipantDto> | null;
}
