import {
  ChangeDetectionStrategy,
  Component,
  inject,
  OnInit,
  signal,
} from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatSnackBar } from '@angular/material/snack-bar';
import { MatTooltipModule } from '@angular/material/tooltip';
import { CsiMkdPremaritalAppBeService } from '../../../api/api-main-app/services';
import { forkJoin } from 'rxjs';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  templateUrl: './dashboard.html',
  imports: [MatCardModule, MatIconModule, MatButtonModule, MatTooltipModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Dashboard implements OnInit {
  private readonly api = inject(CsiMkdPremaritalAppBeService);
  private readonly snackBar = inject(MatSnackBar);

  readonly premaritalCount = signal(0);
  readonly generalCount = signal(0);
  readonly confirmationCount = signal(0);
  readonly totalCount = signal(0);
  
  // Bypass URL generator
  readonly generatedBypassUrl = signal('');

  ngOnInit(): void {
    forkJoin({
      premarital: this.api.apiPremaritalregisterTotalGet(),
      general: this.api.apiGeneralregisterTotalGet(),
      confirmation: this.api.apiConfirmationregisterTotalGet(),
    }).subscribe((results: any) => {
      this.premaritalCount.set(JSON.parse(results.premarital).total);
      this.generalCount.set(JSON.parse(results.general).total);
      this.confirmationCount.set(JSON.parse(results.confirmation).total);

      this.totalCount.set(
        this.premaritalCount() + this.generalCount() + this.confirmationCount()
      );
    });
  }

  /**
   * Generate a time-limited bypass URL for users having CAPTCHA issues
   * Valid for 1 hour from generation time
   */
  generateBypassUrl(): void {
    const timestamp = Date.now();
    const encodedTimestamp = btoa(timestamp.toString());
    const bypassUrl = `${window.location.origin}/register/premarital-register?bypass=${encodedTimestamp}`;
    
    this.generatedBypassUrl.set(bypassUrl);
  }

  /**
   * Copy the generated bypass URL to clipboard
   */
  copyBypassUrl(): void {
    const url = this.generatedBypassUrl();
    if (!url) return;

    navigator.clipboard.writeText(url).then(() => {
      this.snackBar.open(
        $localize`Bypass URL copied to clipboard! Valid for 1 hour.`,
        $localize`Close`,
        { duration: 3000 }
      );
    }).catch(() => {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = url;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      
      this.snackBar.open(
        $localize`Bypass URL copied to clipboard! Valid for 1 hour.`,
        $localize`Close`,
        { duration: 3000 }
      );
    });
  }
}
