/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiGeneralRegisterPost$Params {
      body?: {
'FirstName': string;
'LastName': string;
'FatherName': string;
'Address': string;
'Sex': string;
'Age'?: number;
'Education': string;
'Occupation': string;
'ChurchName'?: string;
'Phone': string;
'Email': string;
'MaritalStatus': string;
'SessionType': string;
'Declaration'?: boolean;
}
}

export function apiGeneralRegisterPost(http: HttpClient, rootUrl: string, params?: ApiGeneralRegisterPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiGeneralRegisterPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiGeneralRegisterPost.PATH = '/api/GeneralRegister';
