// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CsiMkdFunctions.CompiledModels
{
    public partial class ApplicationDbContextModel
    {
        private ApplicationDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("87be09e9-afa1-46fc-8d69-aa362a9c9d85"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var sessionConfiguration = SessionConfigurationEntityType.Create(this);

            SessionConfigurationEntityType.CreateAnnotations(sessionConfiguration);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.6");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
