// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Newtonsoft.Json.Linq;
using csi_mkd_premarital_app_BE.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace csi_mkd_premarital_app_BE.CompiledModels.Cosmos
{
    [EntityFrameworkInternal]
    public partial class AppFeedbackEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "csi_mkd_premarital_app_BE.Models.AppFeedback",
                typeof(AppFeedback),
                baseEntityType,
                discriminatorProperty: "$type",
                discriminatorValue: "AppFeedback",
                propertyCount: 10,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(AppFeedback).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppFeedback).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw);
            id.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            id.AddAnnotation("Cosmos:PropertyName", "id");

            var type = runtimeEntityType.AddProperty(
                "$type",
                typeof(string),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 4000,
                valueGeneratorFactory: new DiscriminatorValueGeneratorFactory().Create);

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTime),
                propertyInfo: typeof(AppFeedback).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppFeedback).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                providerPropertyType: typeof(DateTime),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            var improvements = runtimeEntityType.AddProperty(
                "Improvements",
                typeof(string),
                propertyInfo: typeof(AppFeedback).GetProperty("Improvements", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppFeedback).GetField("<Improvements>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);

            var likedMost = runtimeEntityType.AddProperty(
                "LikedMost",
                typeof(string),
                propertyInfo: typeof(AppFeedback).GetProperty("LikedMost", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppFeedback).GetField("<LikedMost>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);

            var locale = runtimeEntityType.AddProperty(
                "Locale",
                typeof(string),
                propertyInfo: typeof(AppFeedback).GetProperty("Locale", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppFeedback).GetField("<Locale>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 10);

            var page = runtimeEntityType.AddProperty(
                "Page",
                typeof(string),
                propertyInfo: typeof(AppFeedback).GetProperty("Page", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppFeedback).GetField("<Page>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 300);

            var rating = runtimeEntityType.AddProperty(
                "Rating",
                typeof(int),
                propertyInfo: typeof(AppFeedback).GetProperty("Rating", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppFeedback).GetField("<Rating>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var userAgent = runtimeEntityType.AddProperty(
                "UserAgent",
                typeof(string),
                propertyInfo: typeof(AppFeedback).GetProperty("UserAgent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppFeedback).GetField("<UserAgent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);

            var __jObject = runtimeEntityType.AddProperty(
                "__jObject",
                typeof(JObject),
                nullable: true,
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore);
            __jObject.AddAnnotation("Cosmos:PropertyName", "");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Cosmos:ContainerName", "AppFeedbacks");
            runtimeEntityType.AddAnnotation("Cosmos:PartitionKeyNames", new List<string> { "Id" });

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
