// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Newtonsoft.Json.Linq;
using csi_mkd_premarital_app_BE.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace csi_mkd_premarital_app_BE.CompiledModels.Cosmos
{
    [EntityFrameworkInternal]
    public partial class ClassFeedbackRatingsEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "csi_mkd_premarital_app_BE.Models.ClassFeedbackRatings",
                typeof(ClassFeedbackRatings),
                baseEntityType,
                propertyCount: 8,
                foreignKeyCount: 1,
                keyCount: 1);

            var classFeedbackDetailClassFeedbackEntryClassFeedbackid = runtimeEntityType.AddProperty(
                "ClassFeedbackDetailClassFeedbackEntryClassFeedbackid",
                typeof(string),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 4000);

            var classFeedbackDetailClassFeedbackEntryClassFeedbackPremaritalRegistrationId = runtimeEntityType.AddProperty(
                "ClassFeedbackDetailClassFeedbackEntryClassFeedbackPremaritalRegistrationId",
                typeof(Guid),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            classFeedbackDetailClassFeedbackEntryClassFeedbackPremaritalRegistrationId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");

            var classFeedbackDetailClassFeedbackEntryId = runtimeEntityType.AddProperty(
                "ClassFeedbackDetailClassFeedbackEntryId",
                typeof(int),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var engagement = runtimeEntityType.AddProperty(
                "Engagement",
                typeof(int),
                propertyInfo: typeof(ClassFeedbackRatings).GetProperty("Engagement", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClassFeedbackRatings).GetField("<Engagement>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var organization = runtimeEntityType.AddProperty(
                "Organization",
                typeof(int),
                propertyInfo: typeof(ClassFeedbackRatings).GetProperty("Organization", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClassFeedbackRatings).GetField("<Organization>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var quality = runtimeEntityType.AddProperty(
                "Quality",
                typeof(int),
                propertyInfo: typeof(ClassFeedbackRatings).GetProperty("Quality", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClassFeedbackRatings).GetField("<Quality>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var relevance = runtimeEntityType.AddProperty(
                "Relevance",
                typeof(int),
                propertyInfo: typeof(ClassFeedbackRatings).GetProperty("Relevance", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClassFeedbackRatings).GetField("<Relevance>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var __jObject = runtimeEntityType.AddProperty(
                "__jObject",
                typeof(JObject),
                nullable: true,
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore);
            __jObject.AddAnnotation("Cosmos:PropertyName", "");

            var key = runtimeEntityType.AddKey(
                new[] { classFeedbackDetailClassFeedbackEntryClassFeedbackid, classFeedbackDetailClassFeedbackEntryClassFeedbackPremaritalRegistrationId, classFeedbackDetailClassFeedbackEntryId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ClassFeedbackDetailClassFeedbackEntryClassFeedbackid"), declaringEntityType.FindProperty("ClassFeedbackDetailClassFeedbackEntryClassFeedbackPremaritalRegistrationId"), declaringEntityType.FindProperty("ClassFeedbackDetailClassFeedbackEntryId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("ClassFeedbackEntryClassFeedbackid"), principalEntityType.FindProperty("ClassFeedbackEntryClassFeedbackPremaritalRegistrationId"), principalEntityType.FindProperty("ClassFeedbackEntryId") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true,
                requiredDependent: true,
                ownership: true);

            var ratings = principalEntityType.AddNavigation("Ratings",
                runtimeForeignKey,
                onDependent: false,
                typeof(ClassFeedbackRatings),
                propertyInfo: typeof(ClassFeedbackDetail).GetProperty("Ratings", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClassFeedbackDetail).GetField("<Ratings>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                eagerLoaded: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
