// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Newtonsoft.Json.Linq;
using csi_mkd_premarital_app_BE.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace csi_mkd_premarital_app_BE.CompiledModels.Cosmos
{
    [EntityFrameworkInternal]
    public partial class ClassFeedbackTextResponsesEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "csi_mkd_premarital_app_BE.Models.ClassFeedbackTextResponses",
                typeof(ClassFeedbackTextResponses),
                baseEntityType,
                propertyCount: 7,
                foreignKeyCount: 1,
                keyCount: 1);

            var classFeedbackDetailClassFeedbackEntryClassFeedbackid = runtimeEntityType.AddProperty(
                "ClassFeedbackDetailClassFeedbackEntryClassFeedbackid",
                typeof(string),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 4000);

            var classFeedbackDetailClassFeedbackEntryClassFeedbackPremaritalRegistrationId = runtimeEntityType.AddProperty(
                "ClassFeedbackDetailClassFeedbackEntryClassFeedbackPremaritalRegistrationId",
                typeof(Guid),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            classFeedbackDetailClassFeedbackEntryClassFeedbackPremaritalRegistrationId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");

            var classFeedbackDetailClassFeedbackEntryId = runtimeEntityType.AddProperty(
                "ClassFeedbackDetailClassFeedbackEntryId",
                typeof(int),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var comments = runtimeEntityType.AddProperty(
                "Comments",
                typeof(string),
                propertyInfo: typeof(ClassFeedbackTextResponses).GetProperty("Comments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClassFeedbackTextResponses).GetField("<Comments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 4000);

            var improvements = runtimeEntityType.AddProperty(
                "Improvements",
                typeof(string),
                propertyInfo: typeof(ClassFeedbackTextResponses).GetProperty("Improvements", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClassFeedbackTextResponses).GetField("<Improvements>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 4000);

            var valuable = runtimeEntityType.AddProperty(
                "Valuable",
                typeof(string),
                propertyInfo: typeof(ClassFeedbackTextResponses).GetProperty("Valuable", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClassFeedbackTextResponses).GetField("<Valuable>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 4000);

            var __jObject = runtimeEntityType.AddProperty(
                "__jObject",
                typeof(JObject),
                nullable: true,
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore);
            __jObject.AddAnnotation("Cosmos:PropertyName", "");

            var key = runtimeEntityType.AddKey(
                new[] { classFeedbackDetailClassFeedbackEntryClassFeedbackid, classFeedbackDetailClassFeedbackEntryClassFeedbackPremaritalRegistrationId, classFeedbackDetailClassFeedbackEntryId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ClassFeedbackDetailClassFeedbackEntryClassFeedbackid"), declaringEntityType.FindProperty("ClassFeedbackDetailClassFeedbackEntryClassFeedbackPremaritalRegistrationId"), declaringEntityType.FindProperty("ClassFeedbackDetailClassFeedbackEntryId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("ClassFeedbackEntryClassFeedbackid"), principalEntityType.FindProperty("ClassFeedbackEntryClassFeedbackPremaritalRegistrationId"), principalEntityType.FindProperty("ClassFeedbackEntryId") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true,
                requiredDependent: true,
                ownership: true);

            var textResponses = principalEntityType.AddNavigation("TextResponses",
                runtimeForeignKey,
                onDependent: false,
                typeof(ClassFeedbackTextResponses),
                propertyInfo: typeof(ClassFeedbackDetail).GetProperty("TextResponses", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClassFeedbackDetail).GetField("<TextResponses>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                eagerLoaded: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
