// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using csi_mkd_premarital_app_BE.CompiledModels.Cosmos;
using csi_mkd_premarital_app_BE.Data;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(CosmosDbContext), typeof(CosmosDbContextModel))]
