// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace csi_mkd_premarital_app_BE.CompiledModels.Cosmos
{
    public partial class CosmosDbContextModel
    {
        private CosmosDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("0c9d3d6d-fc3d-41e1-8306-05e1bf74dcc4"), entityTypeCount: 7)
        {
        }

        partial void Initialize()
        {
            var appFeedback = AppFeedbackEntityType.Create(this);
            var classFeedback = ClassFeedbackEntityType.Create(this);
            var classFeedbackDetail = ClassFeedbackDetailEntityType.Create(this);
            var classFeedbackEntry = ClassFeedbackEntryEntityType.Create(this);
            var classFeedbackRatings = ClassFeedbackRatingsEntityType.Create(this);
            var classFeedbackTextResponses = ClassFeedbackTextResponsesEntityType.Create(this);
            var questionAnswers = QuestionAnswersEntityType.Create(this);

            ClassFeedbackDetailEntityType.CreateForeignKey1(classFeedbackDetail, classFeedbackEntry);
            ClassFeedbackEntryEntityType.CreateForeignKey1(classFeedbackEntry, classFeedback);
            ClassFeedbackRatingsEntityType.CreateForeignKey1(classFeedbackRatings, classFeedbackDetail);
            ClassFeedbackTextResponsesEntityType.CreateForeignKey1(classFeedbackTextResponses, classFeedbackDetail);

            AppFeedbackEntityType.CreateAnnotations(appFeedback);
            ClassFeedbackEntityType.CreateAnnotations(classFeedback);
            ClassFeedbackDetailEntityType.CreateAnnotations(classFeedbackDetail);
            ClassFeedbackEntryEntityType.CreateAnnotations(classFeedbackEntry);
            ClassFeedbackRatingsEntityType.CreateAnnotations(classFeedbackRatings);
            ClassFeedbackTextResponsesEntityType.CreateAnnotations(classFeedbackTextResponses);
            QuestionAnswersEntityType.CreateAnnotations(questionAnswers);

            AddAnnotation("Cosmos:ContainerName", "CosmosDbContext");
            AddAnnotation("ProductVersion", "10.0.9");
        }
    }
}
