// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Newtonsoft.Json.Linq;
using csi_mkd_premarital_app_BE.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace csi_mkd_premarital_app_BE.CompiledModels.Cosmos
{
    [EntityFrameworkInternal]
    public partial class QuestionAnswersEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "csi_mkd_premarital_app_BE.Models.QuestionAnswers",
                typeof(QuestionAnswers),
                baseEntityType,
                propertyCount: 21,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 4000);
            id.AddAnnotation("Cosmos:PropertyName", "id");

            var ageDifferenceImpact = runtimeEntityType.AddProperty(
                "AgeDifferenceImpact",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("AgeDifferenceImpact", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<AgeDifferenceImpact>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            ageDifferenceImpact.AddAnnotation("Relational:Comment", "Answer to: Impact of age difference");

            var churchImportance = runtimeEntityType.AddProperty(
                "ChurchImportance",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("ChurchImportance", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<ChurchImportance>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            churchImportance.AddAnnotation("Relational:Comment", "Answer to: Importance of church in relationship");

            var definitionOfMarriage = runtimeEntityType.AddProperty(
                "DefinitionOfMarriage",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("DefinitionOfMarriage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<DefinitionOfMarriage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            definitionOfMarriage.AddAnnotation("Relational:Comment", "Answer to: Definition of marriage");

            var eldestYoungestScenario = runtimeEntityType.AddProperty(
                "EldestYoungestScenario",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("EldestYoungestScenario", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<EldestYoungestScenario>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            eldestYoungestScenario.AddAnnotation("Relational:Comment", "Answer to: Eldest/youngest family scenarios");

            var expectationsFromPartner = runtimeEntityType.AddProperty(
                "ExpectationsFromPartner",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("ExpectationsFromPartner", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<ExpectationsFromPartner>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            expectationsFromPartner.AddAnnotation("Relational:Comment", "Answer to: Expectations from partner");

            var familyBackground = runtimeEntityType.AddProperty(
                "FamilyBackground",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("FamilyBackground", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<FamilyBackground>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            familyBackground.AddAnnotation("Relational:Comment", "Answer to: Family background description");

            var fearsAboutMarriage = runtimeEntityType.AddProperty(
                "FearsAboutMarriage",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("FearsAboutMarriage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<FearsAboutMarriage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            fearsAboutMarriage.AddAnnotation("Relational:Comment", "Answer to: Fears about marriage");

            var greatestAdjustment = runtimeEntityType.AddProperty(
                "GreatestAdjustment",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("GreatestAdjustment", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<GreatestAdjustment>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            greatestAdjustment.AddAnnotation("Relational:Comment", "Answer to: Greatest adjustment in marriage");

            var parentsHealthImpact = runtimeEntityType.AddProperty(
                "ParentsHealthImpact",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("ParentsHealthImpact", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<ParentsHealthImpact>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            parentsHealthImpact.AddAnnotation("Relational:Comment", "Answer to: Impact of parents' health on relationship");

            var premaritalRegistrationId = runtimeEntityType.AddProperty(
                "PremaritalRegistrationId",
                typeof(Guid),
                propertyInfo: typeof(QuestionAnswers).GetProperty("PremaritalRegistrationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<PremaritalRegistrationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            premaritalRegistrationId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            premaritalRegistrationId.AddAnnotation("Relational:Comment", "Reference to the premarital registration in PostgreSQL");

            var relationshipWithParentsInlaws = runtimeEntityType.AddProperty(
                "RelationshipWithParentsInlaws",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("RelationshipWithParentsInlaws", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<RelationshipWithParentsInlaws>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            relationshipWithParentsInlaws.AddAnnotation("Relational:Comment", "Answer to: Relationship with parents and in-laws");

            var submittedAt = runtimeEntityType.AddProperty(
                "SubmittedAt",
                typeof(DateTime),
                propertyInfo: typeof(QuestionAnswers).GetProperty("SubmittedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<SubmittedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                providerPropertyType: typeof(DateTime),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            submittedAt.AddAnnotation("Relational:Comment", "Timestamp when the document was created");

            var submitterIpAddress = runtimeEntityType.AddProperty(
                "SubmitterIpAddress",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("SubmitterIpAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<SubmitterIpAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 45);
            submitterIpAddress.AddAnnotation("Relational:Comment", "IP address of the person who submitted the questionnaire");

            var submitterUserAgent = runtimeEntityType.AddProperty(
                "SubmitterUserAgent",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("SubmitterUserAgent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<SubmitterUserAgent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            submitterUserAgent.AddAnnotation("Relational:Comment", "User agent of the browser used to submit the questionnaire");

            var timeWithPartner = runtimeEntityType.AddProperty(
                "TimeWithPartner",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("TimeWithPartner", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<TimeWithPartner>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            timeWithPartner.AddAnnotation("Relational:Comment", "Answer to: Time spent with partner");

            var understandingAboutSex = runtimeEntityType.AddProperty(
                "UnderstandingAboutSex",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("UnderstandingAboutSex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<UnderstandingAboutSex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            understandingAboutSex.AddAnnotation("Relational:Comment", "Answer to: Understanding about sex in marriage");

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTime?),
                propertyInfo: typeof(QuestionAnswers).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                providerPropertyType: typeof(DateTime?));
            updatedAt.AddAnnotation("Relational:Comment", "Timestamp when the document was last updated");

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            version.AddAnnotation("Relational:Comment", "Document schema version for evolution tracking");
            version.AddAnnotation("Relational:DefaultValue", "1.0");

            var wishesConcerns = runtimeEntityType.AddProperty(
                "WishesConcerns",
                typeof(string),
                propertyInfo: typeof(QuestionAnswers).GetProperty("WishesConcerns", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuestionAnswers).GetField("<WishesConcerns>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            wishesConcerns.AddAnnotation("Relational:Comment", "Answer to: Wishes and concerns about marriage");

            var __jObject = runtimeEntityType.AddProperty(
                "__jObject",
                typeof(JObject),
                nullable: true,
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore);
            __jObject.AddAnnotation("Cosmos:PropertyName", "");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Cosmos:ContainerName", "QuestionAnswers");
            runtimeEntityType.AddAnnotation("Cosmos:PartitionKeyNames", new List<string> { "PremaritalRegistrationId" });

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
