/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiPremaritalregisterFilterGet$Params {
  search?: string;
  unapprovedOnly?: boolean;
  activeSessionOnly?: boolean;
  sessionYear?: number;
  sessionName?: string;
  page: number;
  pageSize: number;
}

export function apiPremaritalregisterFilterGet(http: HttpClient, rootUrl: string, params: ApiPremaritalregisterFilterGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiPremaritalregisterFilterGet.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
    rb.query('unapprovedOnly', params.unapprovedOnly, {});
    rb.query('activeSessionOnly', params.activeSessionOnly, {});
    rb.query('sessionYear', params.sessionYear, {});
    rb.query('sessionName', params.sessionName, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiPremaritalregisterFilterGet.PATH = '/api/premaritalregister/filter';
