/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PremaritalOutsideKeralaRegisterDto } from '../../models/premarital-outside-kerala-register-dto';

export interface ApiPremaritalregisterOutsideKeralaIdPut$Params {
  id: string;
      body: PremaritalOutsideKeralaRegisterDto
}

export function apiPremaritalregisterOutsideKeralaIdPut(http: HttpClient, rootUrl: string, params: ApiPremaritalregisterOutsideKeralaIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiPremaritalregisterOutsideKeralaIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiPremaritalregisterOutsideKeralaIdPut.PATH = '/api/premaritalregister-outside-kerala/{id}';
