/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateInstructorDto } from '../../models/create-instructor-dto';
import { InstructorDto } from '../../models/instructor-dto';

export interface ApiInstructorsPost$Params {
      body: CreateInstructorDto
}

export function apiInstructorsPost(http: HttpClient, rootUrl: string, params: ApiInstructorsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<InstructorDto>> {
  const rb = new RequestBuilder(rootUrl, apiInstructorsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InstructorDto>;
    })
  );
}

apiInstructorsPost.PATH = '/api/instructors';
