/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FeedbackResponseDto } from '../../models/feedback-response-dto';

export interface ApiCosmosFeedbackRegistrationRegistrationIdGet$Params {
  registrationId: number;
}

export function apiCosmosFeedbackRegistrationRegistrationIdGet(http: HttpClient, rootUrl: string, params: ApiCosmosFeedbackRegistrationRegistrationIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FeedbackResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, apiCosmosFeedbackRegistrationRegistrationIdGet.PATH, 'get');
  if (params) {
    rb.path('registrationId', params.registrationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FeedbackResponseDto>>;
    })
  );
}

apiCosmosFeedbackRegistrationRegistrationIdGet.PATH = '/api/cosmos/feedback/registration/{registrationId}';
