/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetFeedbackEntriesCountByRegistrationId$Params {
  registrationId: string;
}

export function getFeedbackEntriesCountByRegistrationId(http: HttpClient, rootUrl: string, params: GetFeedbackEntriesCountByRegistrationId$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, getFeedbackEntriesCountByRegistrationId.PATH, 'get');
  if (params) {
    rb.path('registrationId', params.registrationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

getFeedbackEntriesCountByRegistrationId.PATH = '/api/cosmos/feedback/count/{registrationId}';
