/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppFeedbackResponseDto } from '../../models/app-feedback-response-dto';

export interface GetAppFeedback$Params {
}

export function getAppFeedback(http: HttpClient, rootUrl: string, params?: GetAppFeedback$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppFeedbackResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getAppFeedback.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AppFeedbackResponseDto>>;
    })
  );
}

getAppFeedback.PATH = '/api/appfeedback';
