/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { downloadLatestBackup } from '../fn/backup/download-latest-backup';
import { DownloadLatestBackup$Params } from '../fn/backup/download-latest-backup';
import { triggerBackup } from '../fn/backup/trigger-backup';
import { TriggerBackup$Params } from '../fn/backup/trigger-backup';

@Injectable({ providedIn: 'root' })
export class BackupService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `triggerBackup()` */
  static readonly TriggerBackupPath = '/api/backup/trigger';

  /**
   * Manually trigger database backup.
   *
   * Triggers an immediate backup of the Supabase database to Azure Blob Storage
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `triggerBackup()` instead.
   *
   * This method doesn't expect any request body.
   */
  triggerBackup$Response(params?: TriggerBackup$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return triggerBackup(this.http, this.rootUrl, params, context);
  }

  /**
   * Manually trigger database backup.
   *
   * Triggers an immediate backup of the Supabase database to Azure Blob Storage
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `triggerBackup$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  triggerBackup(params?: TriggerBackup$Params, context?: HttpContext): Observable<void> {
    return this.triggerBackup$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `downloadLatestBackup()` */
  static readonly DownloadLatestBackupPath = '/api/backup/download/latest';

  /**
   * Download latest backup.
   *
   * Downloads the most recent backup file from Azure Blob Storage
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadLatestBackup()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadLatestBackup$Response(params?: DownloadLatestBackup$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return downloadLatestBackup(this.http, this.rootUrl, params, context);
  }

  /**
   * Download latest backup.
   *
   * Downloads the most recent backup file from Azure Blob Storage
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadLatestBackup$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadLatestBackup(params?: DownloadLatestBackup$Params, context?: HttpContext): Observable<void> {
    return this.downloadLatestBackup$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
