/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { checkQuestionAnswersExists } from '../fn/question-answers/check-question-answers-exists';
import { CheckQuestionAnswersExists$Params } from '../fn/question-answers/check-question-answers-exists';
import { createQuestionAnswers } from '../fn/question-answers/create-question-answers';
import { CreateQuestionAnswers$Params } from '../fn/question-answers/create-question-answers';
import { deleteQuestionAnswers } from '../fn/question-answers/delete-question-answers';
import { DeleteQuestionAnswers$Params } from '../fn/question-answers/delete-question-answers';
import { getAllQuestionAnswers } from '../fn/question-answers/get-all-question-answers';
import { GetAllQuestionAnswers$Params } from '../fn/question-answers/get-all-question-answers';
import { getQuestionAnswersById } from '../fn/question-answers/get-question-answers-by-id';
import { GetQuestionAnswersById$Params } from '../fn/question-answers/get-question-answers-by-id';
import { getQuestionAnswersByRegistrationId } from '../fn/question-answers/get-question-answers-by-registration-id';
import { GetQuestionAnswersByRegistrationId$Params } from '../fn/question-answers/get-question-answers-by-registration-id';
import { QuestionAnswersResponseDto } from '../models/question-answers-response-dto';
import { updateQuestionAnswers } from '../fn/question-answers/update-question-answers';
import { UpdateQuestionAnswers$Params } from '../fn/question-answers/update-question-answers';

@Injectable({ providedIn: 'root' })
export class QuestionAnswersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllQuestionAnswers()` */
  static readonly GetAllQuestionAnswersPath = '/api/question-answers';

  /**
   * Get all questionnaire answers.
   *
   * Retrieves all questionnaire answers with pagination
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllQuestionAnswers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllQuestionAnswers$Response(params?: GetAllQuestionAnswers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<QuestionAnswersResponseDto>>> {
    return getAllQuestionAnswers(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all questionnaire answers.
   *
   * Retrieves all questionnaire answers with pagination
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllQuestionAnswers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllQuestionAnswers(params?: GetAllQuestionAnswers$Params, context?: HttpContext): Observable<Array<QuestionAnswersResponseDto>> {
    return this.getAllQuestionAnswers$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<QuestionAnswersResponseDto>>): Array<QuestionAnswersResponseDto> => r.body)
    );
  }

  /** Path part for operation `createQuestionAnswers()` */
  static readonly CreateQuestionAnswersPath = '/api/question-answers';

  /**
   * Create new questionnaire answers.
   *
   * Creates new questionnaire answers for a premarital registration
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createQuestionAnswers()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createQuestionAnswers$Response(params: CreateQuestionAnswers$Params, context?: HttpContext): Observable<StrictHttpResponse<QuestionAnswersResponseDto>> {
    return createQuestionAnswers(this.http, this.rootUrl, params, context);
  }

  /**
   * Create new questionnaire answers.
   *
   * Creates new questionnaire answers for a premarital registration
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createQuestionAnswers$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createQuestionAnswers(params: CreateQuestionAnswers$Params, context?: HttpContext): Observable<QuestionAnswersResponseDto> {
    return this.createQuestionAnswers$Response(params, context).pipe(
      map((r: StrictHttpResponse<QuestionAnswersResponseDto>): QuestionAnswersResponseDto => r.body)
    );
  }

  /** Path part for operation `getQuestionAnswersByRegistrationId()` */
  static readonly GetQuestionAnswersByRegistrationIdPath = '/api/question-answers/registration/{registrationId}';

  /**
   * Get questionnaire answers by registration ID.
   *
   * Retrieves questionnaire answers for a specific premarital registration
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getQuestionAnswersByRegistrationId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQuestionAnswersByRegistrationId$Response(params: GetQuestionAnswersByRegistrationId$Params, context?: HttpContext): Observable<StrictHttpResponse<QuestionAnswersResponseDto>> {
    return getQuestionAnswersByRegistrationId(this.http, this.rootUrl, params, context);
  }

  /**
   * Get questionnaire answers by registration ID.
   *
   * Retrieves questionnaire answers for a specific premarital registration
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getQuestionAnswersByRegistrationId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQuestionAnswersByRegistrationId(params: GetQuestionAnswersByRegistrationId$Params, context?: HttpContext): Observable<QuestionAnswersResponseDto> {
    return this.getQuestionAnswersByRegistrationId$Response(params, context).pipe(
      map((r: StrictHttpResponse<QuestionAnswersResponseDto>): QuestionAnswersResponseDto => r.body)
    );
  }

  /** Path part for operation `getQuestionAnswersById()` */
  static readonly GetQuestionAnswersByIdPath = '/api/question-answers/{id}';

  /**
   * Get questionnaire answers by document ID.
   *
   * Retrieves questionnaire answers by document ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getQuestionAnswersById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQuestionAnswersById$Response(params: GetQuestionAnswersById$Params, context?: HttpContext): Observable<StrictHttpResponse<QuestionAnswersResponseDto>> {
    return getQuestionAnswersById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get questionnaire answers by document ID.
   *
   * Retrieves questionnaire answers by document ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getQuestionAnswersById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQuestionAnswersById(params: GetQuestionAnswersById$Params, context?: HttpContext): Observable<QuestionAnswersResponseDto> {
    return this.getQuestionAnswersById$Response(params, context).pipe(
      map((r: StrictHttpResponse<QuestionAnswersResponseDto>): QuestionAnswersResponseDto => r.body)
    );
  }

  /** Path part for operation `updateQuestionAnswers()` */
  static readonly UpdateQuestionAnswersPath = '/api/question-answers/{id}';

  /**
   * Update questionnaire answers.
   *
   * Updates existing questionnaire answers
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateQuestionAnswers()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateQuestionAnswers$Response(params: UpdateQuestionAnswers$Params, context?: HttpContext): Observable<StrictHttpResponse<QuestionAnswersResponseDto>> {
    return updateQuestionAnswers(this.http, this.rootUrl, params, context);
  }

  /**
   * Update questionnaire answers.
   *
   * Updates existing questionnaire answers
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateQuestionAnswers$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateQuestionAnswers(params: UpdateQuestionAnswers$Params, context?: HttpContext): Observable<QuestionAnswersResponseDto> {
    return this.updateQuestionAnswers$Response(params, context).pipe(
      map((r: StrictHttpResponse<QuestionAnswersResponseDto>): QuestionAnswersResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteQuestionAnswers()` */
  static readonly DeleteQuestionAnswersPath = '/api/question-answers/{id}';

  /**
   * Delete questionnaire answers.
   *
   * Deletes questionnaire answers by document ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteQuestionAnswers()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteQuestionAnswers$Response(params: DeleteQuestionAnswers$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteQuestionAnswers(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete questionnaire answers.
   *
   * Deletes questionnaire answers by document ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteQuestionAnswers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteQuestionAnswers(params: DeleteQuestionAnswers$Params, context?: HttpContext): Observable<void> {
    return this.deleteQuestionAnswers$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `checkQuestionAnswersExists()` */
  static readonly CheckQuestionAnswersExistsPath = '/api/question-answers/registration/{registrationId}/exists';

  /**
   * Check if questionnaire answers exist for registration.
   *
   * Checks if questionnaire answers exist for a specific registration
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkQuestionAnswersExists()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkQuestionAnswersExists$Response(params: CheckQuestionAnswersExists$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return checkQuestionAnswersExists(this.http, this.rootUrl, params, context);
  }

  /**
   * Check if questionnaire answers exist for registration.
   *
   * Checks if questionnaire answers exist for a specific registration
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkQuestionAnswersExists$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkQuestionAnswersExists(params: CheckQuestionAnswersExists$Params, context?: HttpContext): Observable<boolean> {
    return this.checkQuestionAnswersExists$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

}
