/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClassFeedbackDto {
  classTitle: string | null;
  comments?: string | null;
  date: string;
  engagementRating?: number;
  improvements?: string | null;
  organizationRating?: number;
  premaritalRegistrationId?: number;
  qualityRating?: number;
  relevanceRating?: number;
  valuable?: string | null;
}
