/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PremaritalRegistration } from '../models/premarital-registration';
export interface ClassFeedback {
  classTitle: string;
  comments?: string | null;
  date: string;
  engagementRating: number;
  id?: number;
  improvements?: string | null;
  organizationRating: number;
  premaritalRegistration?: PremaritalRegistration;
  premaritalRegistrationId: number;
  qualityRating: number;
  relevanceRating: number;
  submittedAt?: string;
  valuable?: string | null;
}
