/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ParticipantDto } from '../models/participant-dto';
export interface ConfirmationRegisterDto {
  churchName: string | null;
  confirmationDate?: string;
  consent?: boolean;
  counsellingDate?: string;
  participants?: Array<ParticipantDto> | null;
  recaptchaToken: string | null;
}
