/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ParticipantDto } from '../models/participant-dto';
export interface ConfirmationRegisterDto {
  ChurchName: string | null;
  ConfirmationDate?: string;
  ConfirmationTime: string | null;
  Consent?: boolean;
  Participants?: Array<ParticipantDto> | null;
}
