/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUpdateSessionDto {
  EndDate?: string;
  Id?: number | null;
  IsActive?: boolean;
  SessionName: string | null;
  StartDate?: string;
  SubmittedDate?: string;
}
