/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmailConfig {
  EmailBodyTemplate?: string | null;
  EmailSubject?: string | null;
  Id?: number;
  SenderEmail?: string | null;
  SenderPassword?: string | null;
}
