/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmailConfig {
  EmailBodyTemplate: string;
  EmailSubject: string;
  Id?: number;
  SenderEmail: string;
  SenderPassword: string;
}
