/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeedbackResponseDto } from '../models/feedback-response-dto';
export interface FeedbackAnalyticsDto {
  averageRatingsByClass?: ({
[key: string]: number;
}) | null;
  feedbackByMonth?: ({
[key: string]: number;
}) | null;
  overallAverageRating?: number;
  recentFeedback?: Array<FeedbackResponseDto> | null;
  totalFeedbackCount?: number;
}
