/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeedbackMetadataDto {
  createdAt?: string;
  instructorName?: string | null;
  location?: string | null;
  platform?: string | null;
  premaritalRegistrationId?: number;
  sessionDuration?: number | null;
  sessionTitle?: string | null;
  source?: string | null;
  version?: string | null;
}
