/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PremaritalRegistration } from '../models/premarital-registration';
export interface PremaritalDocument {
  photoUrl: string;
  premaritalRegistration?: PremaritalRegistration;
  registrationId?: number;
  submittedAt?: string;
  vicarLetterUrl: string;
}
