/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PremaritalDocument } from '../models/premarital-document';
import { SessionConfiguration } from '../models/session-configuration';
export interface PremaritalRegistration {
  address: string;
  age: number;
  churchActivitiesJson: string;
  churchName: string;
  dateOfMarriage?: string | null;
  days: string;
  declaration: boolean;
  education: string;
  email: string;
  fatherName: string;
  fianceName?: string | null;
  firstName: string;
  id?: number;
  lastName: string;
  occupation: string;
  paymentStatus?: boolean;
  phone: string;
  premaritalDocument?: PremaritalDocument;
  sessionConfiguration?: SessionConfiguration;
  sessionId: number;
  sex: string;
  submittedAt?: string;
}
