/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionConfigurationDto {
  EndDate?: string;
  Id?: number;
  IsActive?: boolean;
  SessionName: string | null;
  StartDate?: string;
  SubmittedDate?: string;
}
