/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionFeedbackDto {
  comments?: string | null;
  date: string;
  email: string | null;
  engagementRating?: number;
  firstName: string | null;
  improvements?: string | null;
  lastName: string | null;
  organizationRating?: number;
  qualityRating?: number;
  relevanceRating?: number;
  sessionTitle: string | null;
  valuable?: string | null;
}
