/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionFeedbackDto {
  Comments?: string | null;
  Date: string;
  Email: string | null;
  EngagementRating?: number;
  FirstName: string | null;
  Improvements?: string | null;
  LastName: string | null;
  OrganizationRating?: number;
  QualityRating?: number;
  RelevanceRating?: number;
  SessionTitle: string | null;
  Valuable?: string | null;
}
