/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePasswordDto {
  ConfirmPassword?: string | null;
  CurrentPassword?: string | null;
  NewPassword?: string | null;
}
