/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentStatusUpdateDto } from '../../models/payment-status-update-dto';

export interface ApiPremaritalregisterIdPaymentstatusPut$Params {
  id: number;
      body: PaymentStatusUpdateDto
}

export function apiPremaritalregisterIdPaymentstatusPut(http: HttpClient, rootUrl: string, params: ApiPremaritalregisterIdPaymentstatusPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiPremaritalregisterIdPaymentstatusPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiPremaritalregisterIdPaymentstatusPut.PATH = '/api/premaritalregister/{id}/paymentstatus';
