/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiFeedbackCompletedRegistrationIdGet$Params {
  registrationId: number;
}

export function apiFeedbackCompletedRegistrationIdGet(http: HttpClient, rootUrl: string, params: ApiFeedbackCompletedRegistrationIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<number>>> {
  const rb = new RequestBuilder(rootUrl, apiFeedbackCompletedRegistrationIdGet.PATH, 'get');
  if (params) {
    rb.path('registrationId', params.registrationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<number>>;
    })
  );
}

apiFeedbackCompletedRegistrationIdGet.PATH = '/api/feedback/completed/{registrationId}';
