/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SessionConfigurationDto } from '../../models/session-configuration-dto';

export interface ApiSessionconfigGet$Params {
}

export function apiSessionconfigGet(http: HttpClient, rootUrl: string, params?: ApiSessionconfigGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SessionConfigurationDto>>> {
  const rb = new RequestBuilder(rootUrl, apiSessionconfigGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SessionConfigurationDto>>;
    })
  );
}

apiSessionconfigGet.PATH = '/api/sessionconfig';
