/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GeneralDocumentDto } from '../../models/general-document-dto';

export interface ApiGeneralregisterSavePhotoUrlPost$FormData$Params {
      body?: GeneralDocumentDto
}

export function apiGeneralregisterSavePhotoUrlPost$FormData(http: HttpClient, rootUrl: string, params?: ApiGeneralregisterSavePhotoUrlPost$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiGeneralregisterSavePhotoUrlPost$FormData.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiGeneralregisterSavePhotoUrlPost$FormData.PATH = '/api/generalregister/save-photo-url';
