/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiAzureUploadGenerateSasGet$Params {
  fileName?: string;
  contentType?: string;
}

export function apiAzureUploadGenerateSasGet(http: HttpClient, rootUrl: string, params?: ApiAzureUploadGenerateSasGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiAzureUploadGenerateSasGet.PATH, 'get');
  if (params) {
    rb.query('fileName', params.fileName, {});
    rb.query('contentType', params.contentType, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiAzureUploadGenerateSasGet.PATH = '/api/AzureUpload/generate-sas';
