/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAzureUploadGenerateSasGet } from '../fn/azure-upload/api-azure-upload-generate-sas-get';
import { ApiAzureUploadGenerateSasGet$Params } from '../fn/azure-upload/api-azure-upload-generate-sas-get';

@Injectable({ providedIn: 'root' })
export class AzureUploadService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAzureUploadGenerateSasGet()` */
  static readonly ApiAzureUploadGenerateSasGetPath = '/api/AzureUpload/generate-sas';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAzureUploadGenerateSasGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAzureUploadGenerateSasGet$Response(params?: ApiAzureUploadGenerateSasGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiAzureUploadGenerateSasGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAzureUploadGenerateSasGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAzureUploadGenerateSasGet(params?: ApiAzureUploadGenerateSasGet$Params, context?: HttpContext): Observable<void> {
    return this.apiAzureUploadGenerateSasGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
