/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiConfirmationRegisterFilterGet } from '../fn/confirmation-register/api-confirmation-register-filter-get';
import { ApiConfirmationRegisterFilterGet$Params } from '../fn/confirmation-register/api-confirmation-register-filter-get';
import { apiConfirmationRegisterPost } from '../fn/confirmation-register/api-confirmation-register-post';
import { ApiConfirmationRegisterPost$Params } from '../fn/confirmation-register/api-confirmation-register-post';
import { apiConfirmationRegisterSaveFileUrlPost } from '../fn/confirmation-register/api-confirmation-register-save-file-url-post';
import { ApiConfirmationRegisterSaveFileUrlPost$Params } from '../fn/confirmation-register/api-confirmation-register-save-file-url-post';

@Injectable({ providedIn: 'root' })
export class ConfirmationRegisterService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiConfirmationRegisterPost()` */
  static readonly ApiConfirmationRegisterPostPath = '/api/ConfirmationRegister';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiConfirmationRegisterPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiConfirmationRegisterPost$Response(params?: ApiConfirmationRegisterPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiConfirmationRegisterPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiConfirmationRegisterPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiConfirmationRegisterPost(params?: ApiConfirmationRegisterPost$Params, context?: HttpContext): Observable<void> {
    return this.apiConfirmationRegisterPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiConfirmationRegisterSaveFileUrlPost()` */
  static readonly ApiConfirmationRegisterSaveFileUrlPostPath = '/api/ConfirmationRegister/save-file-url';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiConfirmationRegisterSaveFileUrlPost()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiConfirmationRegisterSaveFileUrlPost$Response(params?: ApiConfirmationRegisterSaveFileUrlPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiConfirmationRegisterSaveFileUrlPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiConfirmationRegisterSaveFileUrlPost$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiConfirmationRegisterSaveFileUrlPost(params?: ApiConfirmationRegisterSaveFileUrlPost$Params, context?: HttpContext): Observable<void> {
    return this.apiConfirmationRegisterSaveFileUrlPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiConfirmationRegisterFilterGet()` */
  static readonly ApiConfirmationRegisterFilterGetPath = '/api/ConfirmationRegister/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiConfirmationRegisterFilterGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiConfirmationRegisterFilterGet$Response(params?: ApiConfirmationRegisterFilterGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiConfirmationRegisterFilterGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiConfirmationRegisterFilterGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiConfirmationRegisterFilterGet(params?: ApiConfirmationRegisterFilterGet$Params, context?: HttpContext): Observable<void> {
    return this.apiConfirmationRegisterFilterGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
