/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { healthGet } from '../fn/csi-mkd-premarital-app-be/health-get';
import { HealthGet$Params } from '../fn/csi-mkd-premarital-app-be/health-get';

@Injectable({ providedIn: 'root' })
export class CsiMkdPremaritalAppBeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `healthGet()` */
  static readonly HealthGetPath = '/health';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `healthGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthGet$Response(params?: HealthGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return healthGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `healthGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthGet(params?: HealthGet$Params, context?: HttpContext): Observable<void> {
    return this.healthGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
