/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiPremaritalRegisterCheckEmailGet } from '../fn/premarital-register/api-premarital-register-check-email-get';
import { ApiPremaritalRegisterCheckEmailGet$Params } from '../fn/premarital-register/api-premarital-register-check-email-get';
import { apiPremaritalRegisterFilterGet } from '../fn/premarital-register/api-premarital-register-filter-get';
import { ApiPremaritalRegisterFilterGet$Params } from '../fn/premarital-register/api-premarital-register-filter-get';
import { apiPremaritalRegisterIdPaymentstatusPut } from '../fn/premarital-register/api-premarital-register-id-paymentstatus-put';
import { ApiPremaritalRegisterIdPaymentstatusPut$Params } from '../fn/premarital-register/api-premarital-register-id-paymentstatus-put';
import { apiPremaritalRegisterPost } from '../fn/premarital-register/api-premarital-register-post';
import { ApiPremaritalRegisterPost$Params } from '../fn/premarital-register/api-premarital-register-post';

@Injectable({ providedIn: 'root' })
export class PremaritalRegisterService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiPremaritalRegisterPost()` */
  static readonly ApiPremaritalRegisterPostPath = '/api/PremaritalRegister';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPremaritalRegisterPost()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiPremaritalRegisterPost$Response(params?: ApiPremaritalRegisterPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiPremaritalRegisterPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPremaritalRegisterPost$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiPremaritalRegisterPost(params?: ApiPremaritalRegisterPost$Params, context?: HttpContext): Observable<void> {
    return this.apiPremaritalRegisterPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiPremaritalRegisterIdPaymentstatusPut()` */
  static readonly ApiPremaritalRegisterIdPaymentstatusPutPath = '/api/PremaritalRegister/{id}/paymentstatus';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPremaritalRegisterIdPaymentstatusPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiPremaritalRegisterIdPaymentstatusPut$Response(params: ApiPremaritalRegisterIdPaymentstatusPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiPremaritalRegisterIdPaymentstatusPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPremaritalRegisterIdPaymentstatusPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiPremaritalRegisterIdPaymentstatusPut(params: ApiPremaritalRegisterIdPaymentstatusPut$Params, context?: HttpContext): Observable<void> {
    return this.apiPremaritalRegisterIdPaymentstatusPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiPremaritalRegisterCheckEmailGet()` */
  static readonly ApiPremaritalRegisterCheckEmailGetPath = '/api/PremaritalRegister/check-email';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPremaritalRegisterCheckEmailGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPremaritalRegisterCheckEmailGet$Response(params?: ApiPremaritalRegisterCheckEmailGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiPremaritalRegisterCheckEmailGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPremaritalRegisterCheckEmailGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPremaritalRegisterCheckEmailGet(params?: ApiPremaritalRegisterCheckEmailGet$Params, context?: HttpContext): Observable<void> {
    return this.apiPremaritalRegisterCheckEmailGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiPremaritalRegisterFilterGet()` */
  static readonly ApiPremaritalRegisterFilterGetPath = '/api/PremaritalRegister/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPremaritalRegisterFilterGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPremaritalRegisterFilterGet$Response(params?: ApiPremaritalRegisterFilterGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiPremaritalRegisterFilterGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPremaritalRegisterFilterGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPremaritalRegisterFilterGet(params?: ApiPremaritalRegisterFilterGet$Params, context?: HttpContext): Observable<void> {
    return this.apiPremaritalRegisterFilterGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
