/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiSessionconfigGet } from '../fn/session-config/api-sessionconfig-get';
import { ApiSessionconfigGet$Params } from '../fn/session-config/api-sessionconfig-get';
import { apiSessionconfigIdDelete } from '../fn/session-config/api-sessionconfig-id-delete';
import { ApiSessionconfigIdDelete$Params } from '../fn/session-config/api-sessionconfig-id-delete';
import { apiSessionconfigIdGet } from '../fn/session-config/api-sessionconfig-id-get';
import { ApiSessionconfigIdGet$Params } from '../fn/session-config/api-sessionconfig-id-get';
import { apiSessionconfigIdPut } from '../fn/session-config/api-sessionconfig-id-put';
import { ApiSessionconfigIdPut$Params } from '../fn/session-config/api-sessionconfig-id-put';
import { apiSessionconfigPost } from '../fn/session-config/api-sessionconfig-post';
import { ApiSessionconfigPost$Params } from '../fn/session-config/api-sessionconfig-post';
import { apiSessionconfigSessionsGet } from '../fn/session-config/api-sessionconfig-sessions-get';
import { ApiSessionconfigSessionsGet$Params } from '../fn/session-config/api-sessionconfig-sessions-get';

@Injectable({ providedIn: 'root' })
export class SessionConfigService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiSessionconfigGet()` */
  static readonly ApiSessionconfigGetPath = '/api/sessionconfig';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigGet$Response(params?: ApiSessionconfigGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiSessionconfigGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigGet(params?: ApiSessionconfigGet$Params, context?: HttpContext): Observable<void> {
    return this.apiSessionconfigGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiSessionconfigPost()` */
  static readonly ApiSessionconfigPostPath = '/api/sessionconfig';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSessionconfigPost$Response(params?: ApiSessionconfigPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiSessionconfigPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSessionconfigPost(params?: ApiSessionconfigPost$Params, context?: HttpContext): Observable<void> {
    return this.apiSessionconfigPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiSessionconfigIdGet()` */
  static readonly ApiSessionconfigIdGetPath = '/api/sessionconfig/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigIdGet$Response(params: ApiSessionconfigIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiSessionconfigIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigIdGet(params: ApiSessionconfigIdGet$Params, context?: HttpContext): Observable<void> {
    return this.apiSessionconfigIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiSessionconfigIdPut()` */
  static readonly ApiSessionconfigIdPutPath = '/api/sessionconfig/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSessionconfigIdPut$Response(params: ApiSessionconfigIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiSessionconfigIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSessionconfigIdPut(params: ApiSessionconfigIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiSessionconfigIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiSessionconfigIdDelete()` */
  static readonly ApiSessionconfigIdDeletePath = '/api/sessionconfig/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigIdDelete$Response(params: ApiSessionconfigIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiSessionconfigIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigIdDelete(params: ApiSessionconfigIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiSessionconfigIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiSessionconfigSessionsGet()` */
  static readonly ApiSessionconfigSessionsGetPath = '/api/sessionconfig/sessions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigSessionsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigSessionsGet$Response(params?: ApiSessionconfigSessionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiSessionconfigSessionsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigSessionsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigSessionsGet(params?: ApiSessionconfigSessionsGet$Params, context?: HttpContext): Observable<void> {
    return this.apiSessionconfigSessionsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
