/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiSessionconfigGet$Json } from '../fn/session-config/api-sessionconfig-get-json';
import { ApiSessionconfigGet$Json$Params } from '../fn/session-config/api-sessionconfig-get-json';
import { apiSessionconfigGet$Plain } from '../fn/session-config/api-sessionconfig-get-plain';
import { ApiSessionconfigGet$Plain$Params } from '../fn/session-config/api-sessionconfig-get-plain';
import { apiSessionconfigIdDelete } from '../fn/session-config/api-sessionconfig-id-delete';
import { ApiSessionconfigIdDelete$Params } from '../fn/session-config/api-sessionconfig-id-delete';
import { apiSessionconfigIdGet$Json } from '../fn/session-config/api-sessionconfig-id-get-json';
import { ApiSessionconfigIdGet$Json$Params } from '../fn/session-config/api-sessionconfig-id-get-json';
import { apiSessionconfigIdGet$Plain } from '../fn/session-config/api-sessionconfig-id-get-plain';
import { ApiSessionconfigIdGet$Plain$Params } from '../fn/session-config/api-sessionconfig-id-get-plain';
import { apiSessionconfigIdPut } from '../fn/session-config/api-sessionconfig-id-put';
import { ApiSessionconfigIdPut$Params } from '../fn/session-config/api-sessionconfig-id-put';
import { apiSessionconfigPost$Json } from '../fn/session-config/api-sessionconfig-post-json';
import { ApiSessionconfigPost$Json$Params } from '../fn/session-config/api-sessionconfig-post-json';
import { apiSessionconfigPost$Plain } from '../fn/session-config/api-sessionconfig-post-plain';
import { ApiSessionconfigPost$Plain$Params } from '../fn/session-config/api-sessionconfig-post-plain';
import { SessionConfigurationDto } from '../models/session-configuration-dto';

@Injectable({ providedIn: 'root' })
export class SessionConfigService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiSessionconfigGet()` */
  static readonly ApiSessionconfigGetPath = '/api/sessionconfig';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigGet$Plain$Response(params?: ApiSessionconfigGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SessionConfigurationDto>>> {
    return apiSessionconfigGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigGet$Plain(params?: ApiSessionconfigGet$Plain$Params, context?: HttpContext): Observable<Array<SessionConfigurationDto>> {
    return this.apiSessionconfigGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SessionConfigurationDto>>): Array<SessionConfigurationDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigGet$Json$Response(params?: ApiSessionconfigGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SessionConfigurationDto>>> {
    return apiSessionconfigGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigGet$Json(params?: ApiSessionconfigGet$Json$Params, context?: HttpContext): Observable<Array<SessionConfigurationDto>> {
    return this.apiSessionconfigGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SessionConfigurationDto>>): Array<SessionConfigurationDto> => r.body)
    );
  }

  /** Path part for operation `apiSessionconfigPost()` */
  static readonly ApiSessionconfigPostPath = '/api/sessionconfig';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSessionconfigPost$Plain$Response(params?: ApiSessionconfigPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionConfigurationDto>> {
    return apiSessionconfigPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSessionconfigPost$Plain(params?: ApiSessionconfigPost$Plain$Params, context?: HttpContext): Observable<SessionConfigurationDto> {
    return this.apiSessionconfigPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<SessionConfigurationDto>): SessionConfigurationDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSessionconfigPost$Json$Response(params?: ApiSessionconfigPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionConfigurationDto>> {
    return apiSessionconfigPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSessionconfigPost$Json(params?: ApiSessionconfigPost$Json$Params, context?: HttpContext): Observable<SessionConfigurationDto> {
    return this.apiSessionconfigPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<SessionConfigurationDto>): SessionConfigurationDto => r.body)
    );
  }

  /** Path part for operation `apiSessionconfigIdGet()` */
  static readonly ApiSessionconfigIdGetPath = '/api/sessionconfig/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigIdGet$Plain$Response(params: ApiSessionconfigIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionConfigurationDto>> {
    return apiSessionconfigIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigIdGet$Plain(params: ApiSessionconfigIdGet$Plain$Params, context?: HttpContext): Observable<SessionConfigurationDto> {
    return this.apiSessionconfigIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<SessionConfigurationDto>): SessionConfigurationDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigIdGet$Json$Response(params: ApiSessionconfigIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionConfigurationDto>> {
    return apiSessionconfigIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigIdGet$Json(params: ApiSessionconfigIdGet$Json$Params, context?: HttpContext): Observable<SessionConfigurationDto> {
    return this.apiSessionconfigIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<SessionConfigurationDto>): SessionConfigurationDto => r.body)
    );
  }

  /** Path part for operation `apiSessionconfigIdPut()` */
  static readonly ApiSessionconfigIdPutPath = '/api/sessionconfig/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSessionconfigIdPut$Response(params: ApiSessionconfigIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiSessionconfigIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSessionconfigIdPut(params: ApiSessionconfigIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiSessionconfigIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiSessionconfigIdDelete()` */
  static readonly ApiSessionconfigIdDeletePath = '/api/sessionconfig/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSessionconfigIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigIdDelete$Response(params: ApiSessionconfigIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiSessionconfigIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSessionconfigIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSessionconfigIdDelete(params: ApiSessionconfigIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiSessionconfigIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
