/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AdminLoginDto } from './models/admin-login-dto';
export type { CheckEmailResponseDto } from './models/check-email-response-dto';
export type { ClassFeedback } from './models/class-feedback';
export type { ClassFeedbackDto } from './models/class-feedback-dto';
export type { ConfirmationDocumentDto } from './models/confirmation-document-dto';
export type { ConfirmationRegisterDto } from './models/confirmation-register-dto';
export type { CreateUpdateSessionDto } from './models/create-update-session-dto';
export type { EmailConfig } from './models/email-config';
export type { GeneralDocumentDto } from './models/general-document-dto';
export type { GeneralRegisterDto } from './models/general-register-dto';
export type { ParticipantDto } from './models/participant-dto';
export type { PaymentStatusUpdateDto } from './models/payment-status-update-dto';
export type { PremaritalDocument } from './models/premarital-document';
export type { PremaritalDocumentDto } from './models/premarital-document-dto';
export type { PremaritalRegisterDto } from './models/premarital-register-dto';
export type { PremaritalRegistration } from './models/premarital-registration';
export type { SessionConfiguration } from './models/session-configuration';
export type { SessionConfigurationDto } from './models/session-configuration-dto';
export type { UpdatePasswordDto } from './models/update-password-dto';
